apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::955982447562:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::955982447562:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5UDM327MERFB
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-17T16:25:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "58496"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 951f849e-a676-404e-86a4-fb1c09e2f229
